# CAFE 24 주문 요청 테스트

POST {{$dotenv BASE_URL}}?eventType=CAFE24_ORDER
Content-Type: application/json
X-API-Key: {{$dotenv CAFE24_API_KEY}}
X-Trace-ID: 60fb413c-ab5d-46c6-9e91-b8250af27622

{
  "event_no": 90023,
  "resource":{
    "mall_id":"cafe24bestshop",
    "event_shop_no":"1",
    "event_code":"create_order",
    "order_id":"20200717-0029236",
    "payment_gateway_name":"",
    "currency":"KRW",
    "order_date":"2020-07-17T15:28:14+09:00",
    "order_place_name":"naver pay",
    "member_id":"gdhong",
    "member_authentication":null,
    "buyer_name":"Jessica Hong",
    "buyer_email":"gdhong@cafe24corp.com",
    "buyer_phone":"02-0000-0000",
    "buyer_cellphone":"010-2424-2424",
    "group_no_when_ordering":"",
    "first_order":null,
    "order_from_mobile":"F",
    "paid":"T",
    "payment_date":"2020-07-17T15:24:07+09:00",
    "billing_name":"Jessica Hong",
    "bank_code":null,
    "payment_method":"mileage",
    "easypay_name":"",
    "use_escrow":"F",
    "bank_account_no":"",
    "order_price_amount":"24680.00",
    "membership_discount_amount":"0.00",
    "actual_payment_amount":"0.00",
    "mileage_spent_amount":"0.00",
    "shipping_fee":"0.00",
    "shipping_type":"A",
    "shipping_status":"F",
    "wished_delivery_date":"0000-00-00",
    "wished_delivery_time":null,
    "store_pickup":"F",
    "shipping_message":"",
    "order_place_id":"NCHECKOUT",
    "ordering_product_code":"P00000BO,P00000DQ",
    "ordering_product_name":"Sample Product Name 1,Sample Product Name 2"
  }
}